### PR TITLE
Fix message to iov

### PR DESCRIPTION
**Pull request by mstanichenko**
Hi Pekka,

Please have a look at a simple but in some cases very useful feature which I want to add.
I pretty much described everything in a commit message but feel free to ask if something
is not clear enough.

Marat

### CODE REVIEW

**Comment by divaykin** [comment]
@mstanichenko by the way I do logging by replacing send/recv
```
static ssize_t log_sendmsg(int fd, struct iovec *iov, size_t length, int flags) {
	struct msghdr msg {};
	msg.msg_iov	   = iov,
	msg.msg_iovlen = length;
	std::cout << "T: ";
	for (size_t i = 0; i < length; ++i) std::cout << fix_pretty(iov[i].iov_base, iov[i].iov_len);
	std::cout << std::endl << std::endl;
	return sendmsg(fd, &msg, flags);
}

static ssize_t log_recv(int fd, void *buf, size_t n, int flags) {
	auto len = recv(fd, buf, n, flags);
	if (len > 0) std::cout << "R: " << fix_pretty(buf, len) << std::endl << std::endl;
	return len;
}```

**Comment by mstanichenko** [comment]
You are right @divaykin.
This functionality was amost in the code.
It just needs to be well-pronounced.

**Comment by divaykin** [comment]
@mstanichenko maybe you can think of something similar for `recv`?

**Comment by mstanichenko** [comment]
@divaykin, I didn't get your last point actually. The solution proposed serves for both purposes It covers both receiving and sending parts. Did I miss something?

**Comment by divaykin** [comment]
you right @mstanichenko there is indeed `recv` part (in `parse`). could you please make delimiter arbitrary char? you won't believe but sometimes `|` is present in message text so I use `@` or whatever. plus would be great to have `fprint_iov` to be able to print any `struct msghdr *` in addition to `struct fix_message *`. maybe we can even put `struct msghdr` into `fix_message` so it can hold arbitrary length vectors.

**Comment by mstanichenko** [comment]
```msg->iov``` is a pointer to the raw data with a natural FIX delimiter which is SOH (0x01).
Technically speaking, ```fprintmsg_iov``` is not a part of a library. It is just an example which I put under the tools. It is not supposed to be neither general nor efficient. BTW I still don't really get you. What extra information you want to log?

Besides, AFAICT efficient logging technique is a different topic which stays beyond our library

**Comment by divaykin** [comment]
if `fprintmsg_iov` is fine then if it's not a part of a library, never mind then, thanks

**Pull request merged**
