### PR TITLE
new function returning nr bytes read from socket or -1 if none

### PR DESCRIPTION
**Pull request by divaykin**
#45 @mstanichenko @penberg please review

### CODE REVIEW

**Comment by mstanichenko** [comment]
int fix_session_recv(fix_session *self, fix_message **msg, int flags)

**Comment by mstanichenko** [comment]
```
int fix_session_recv(fix_session *self, fix_message **msg, int flags)
```

**Comment by divaykin** [comment]
Agreed `int fix_session_recv(fix_session *self, fix_message **msg, int flags)` is better (can be interpreted as receiving array of messages though). Will do it this way and will try to not break the compatibility.

**Comment by divaykin** [comment]
Regarding error codes - basically `len = 0` is not an error it just indicated connection is closed. But there could be really OS level error as well. What's your view on reporting the following situations:
1. Nothing was read, just a message was parsed from already received buffers
2. Zero bytes received (connection closed)
3. OS level error (recv returns -1) with errno

What shall `fix_session_recv` return in three cases above?

**Comment by mstanichenko** [comment]
fix_session_recv() possible errors are not just about OS. It could be a garbled message or potential libtrading internal problems. So, I believe fix_session_recv() should return the number of successfully decoded messages (0 or 1 in current setup) or -1 in case of any special situation (including closed connection). If one needs a real reason behind, he should address fix_session structure for details. We can implement some interface between a user and a session structure which will help to get fine grained information about the error (OS level error, connection is closed or library specific one). The same applies for fix_session_send().

As to compatibility, I personally do not see any problem if you break some. Library API has quite some room for improvement and missing functionality has to be filled eventually. Feel free to implement things which are convenient for your needs and make sense in general. I believe, we will have a chance to discuss details then.

**Comment by divaykin** [comment]
@mstanichenko thanks, got it

**Comment by divaykin** [comment]
@mstanichenko @penberg here you go, better?

**Comment by mstanichenko** [comment]
Hi Denis, sorry for delay. I had a limited Internet access.

Perfect!

Changes look OK to me. Just a few observations:

a) There is a trailing whitespace lib/proto/fix_session.c:214
b) Is there a difference between 'res' and 'msg' here? Why do we call it differently?

```
int fix_session_send(struct fix_session *self, struct fix_message *msg, int flags);
int fix_session_recv(struct fix_session *self, struct fix_message **res, int flags);
```
c) We are not using fix_message_parse() return value right now (lib/proto/fix_session.c:217)
At some point in the future we probably need to adjust that.

@penberg, do you have any comments? Could you please merge these changes?

**Comment by penberg** [comment]
@mstanichenko @divaykin I'm fine with the changes but I'd like to see them squashed in one commit to keep the history clean. You can force push to the Github remote branch and the pull request is automatically updated.

**Comment by divaykin** [comment]
@mstanichenko I've renamed `**res` to `**msg` in .h file but left it as is .c as I need another variable called `msg`. thanks guys, I like your code review a lot ) no space character would left unnoticed!

**Comment by divaykin** [comment]
@penberg thanks, here you go

**Comment by penberg** [comment]
Pulled, thanks a lot!

**Pull request merged**
