### PR TITLE
templates support - new version of canned messages

### PR DESCRIPTION
**Pull request by divaykin**
@penberg @mstanichenko this is my second attempt to nicely incorporate templates. could you please share your thoughts? many thanks

Denis

### CODE REVIEW

**Comment by divaykin** [comment]
guys if you think it's a too big of a feature I can just put it into private part of my code

**Comment by penberg** [comment]
@divaykin I'm strongly in favor for this feature but I'd really like to hear @mstanichenko's comments before merging. Can you please rebase the branch and drop the merge and revert of your previous branch to keep git history clean?

**Comment by divaykin** [comment]
@penberg rebased, thanks

**Comment by mstanichenko** [comment]
Hi @divaykin and @penberg !

Please find my comments below (with no particular order of importance):

1.
```C
include/libtrading/proto/fix_message.h

+const char *fix_msg_types[FIX_MSG_TYPE_MAX];
```
```C
lib/proto/fix_message.c

-static const char *fix_msg_types[FIX_MSG_TYPE_MAX] = {
+const char *fix_msg_types[FIX_MSG_TYPE_MAX] = {
```

I am not sure what was the idea behind but please do not do that. This is a real source of multiple definitions.

2.
```C
+static void strreverse(char* begin, char* end)
+static size_t modp_litoa10_zpad(int64_t value, int zpad, char* str)
```

Why can't we have just a single place for all string encoding/decoding functionality?
It would allow us to reuse the code and not copy it all over the library.

3.
```C
+#define FIX_TEMPLATE_BODY_LEN_ZPAD 4
+#define FIX_TEMPLATE_MSG_SEQ_NUM_ZPAD 6
+#define FIX_MAX_CSUM_LEN 16UL
```
Any reason why ```FIX_MAX_CSUM``` is defined other than ```FIX_TEMPLATE_BODY_LEN_ZPAD``` or ```FIX_TEMPLATE_MSG_SEQ_NUM_ZPAD```?

4.
```C
lib/proto/fix_template.c

+void fix_template_prepare(struct fix_template *self, const char *begin_string, enum fix_msg_type msg_type, const char *sender_comp_id, const char *target_comp_id, const unsigned long nr_const_fields, struct fix_field *const_fields)
```
Too many input arguments. I'd suggest using auxiliary template configuration structure.
See ```fix_session_new()``` for example

5.
I like your way of using templates in ```tools/fix/fix_perf.c```. That really makes it clear why we need this feature and how one is supposed to use it. Nevertheless, a [good commit message](https://github.com/torvalds/subsurface/blob/master/README#L87) is always nice to have :smirk:

6.
```C
+struct fix_template {
+	char			*marker_body_length;
+	char			*marker_msg_seq_num;
+	char			*marker_sender_comp_id;
+	char			*marker_sending_time;
+	char			*marker_check_sum;
```

I am not really good at naming... Is it really the case that ```marker_*``` is just a pointer to a FIX field value?

7.
```C
+	modp_litoa10_zpad(buffer_size(self->body_buf) + buffer_size(self->const_buf), FIX_TEMPLATE_BODY_LEN_ZPAD, self->marker_body_length);
+	modp_litoa10_zpad(session->out_msg_seq_num, FIX_TEMPLATE_MSG_SEQ_NUM_ZPAD, self->marker_msg_seq_num);
```

Not a safe call. A source of NULL dereferencing.

8.
```C
...
// assume all sender_comp_id are of the same size
...
// assume target_comp_id is static
```
You make implicit assumptions here e.g. ```target_comp_id``` and ```sender_comp_id``` have different properties. How general are these assumptions? It worth having a well document format which explains what each of template fields means and what are the expected values.

For example,
```C
+	struct buffer		*head_buf;	/* first three fields */
```
This does not seem to be true as ```head_buf``` is just two fields but not three, isn't it?

9.
```C
+	self->const_csum = buffer_sum(self->const_buf);
```

Assigned but never used. Can't we use it in ```fix_template_unparse()```?

10.
```C
+	buffer_printf(rx_buf, "%.*s%.*s%.*s%.*s\n", (int)buffer_size(template->head_buf), buffer_start(template->head_buf), (int)buffer_size(template->const_buf), buffer_start(template->const_buf), (int)buffer_size(template->body_buf), buffer_start(template->body_buf), (int)buffer_size(template->csum_buf), buffer_start(template->csum_buf));
```

This is a very long line. I do realize that 80 symbols line may not be a mandatory requirement
nowadays but it is a good reference point :smile:

11.
```C
tools/fix/fix_perf.c

int main(int argc, char *argv[])
```
```main()``` became rather huge as it tests libtrading performance in many aspects. It worth having one function (if possible) per feature tested.

12.

```C
tools/fix/fix_perf.c

...
msg = fix_message_new();
...
template = fix_template_new();
...
rx_msg = fix_message_new();
...
```

Memory leaks in ```fix_perf```

Overall, I would like this feature to be included. The more it will be used the more attractive interface it will have. I also like that both ways (the old one and the new one) are still available.

**Comment by divaykin** [comment]
Hi @mstanichenko 

I really appreciate your review and help. Many thanks!

1.
```c
include/libtrading/proto/fix_message.h

+const char *fix_msg_types[FIX_MSG_TYPE_MAX];
```
this is needed here https://github.com/divaykin/libtrading/blob/templates-support/lib/proto/fix_template.c#L135 to get MsgType string during formatting. i really need it to be public.

2.
> single place for all string encoding/decoding
agreed it's suboptimal but @penberg imported https://github.com/divaykin/libtrading/blob/templates-support/lib/stringencoders/modp_numtoa.c stringencoders library into the project and essentially it's not desirable to modify these files as our version could diverge from source a lot. i think even you was against tweaking these files? I can place it to this file perhaps? https://github.com/divaykin/libtrading/blob/templates-support/lib/itoa.c

3. 
`FIX_MAX_CSUM` has a bit different meaning - it's a length of `csum` buffer. other constants are number of symbols in `BodyLen` and `MsgSeqNum` fields. i can rename it, don't feel strong one way or another

6.
`marker_*` is indeed a pointer to FIX field value. happy to rename.

7.
> Not a safe call. A source of NULL dereferencing.
you mean dereference of `self` or `session`? we've very little `!= NULL` checks actually all over the library. should we add it on this one place?

8.
`target_comp_id` constant - it's often the case, typically it's an exchange name (`CME`, `ICE`, etc). but of course it applies only to "buy" side. fixed size of `sender_comp_id` - difficult to judge, this is where we may need improvements but i'd suggest to keep it for now.

12.
there are different views on whether freeing memory right before exit is a memory leak or a waste of CPU cycles )



the rest of the points - i'll try to improve the stuff. also of course i'd need to implement template send

**Comment by mstanichenko** [comment]
1.
> i really need it to be public

I don't see any problems here. Just move initialization to ```include/libtrading/proto/fix_message.h```
The problem as I can see it is that you rely on a particular order of initialization in different translation units. AFAIK, C99 doesn't provide any guarantees. Are there any guarantees that ```fix_msg_types``` will have correct values (and not zeros) if you include a header somewhere else?

2.
> i think even you was against tweaking these files?

Yes, I was

> I can place it to this file perhaps?

Agreed, there should be a single place for all such things. I do not mind if we will be using that file for the time being.

3.

> FIX_MAX_CSUM has a bit different meaning - it's a length of csum buffer. other constants are  number of symbols in BodyLen and MsgSeqNum fields. i can rename it, don't feel strong one way or another

No, I am not against the way they're named. I was just curious why ```FIX_MAX_CSUM``` integer literal was marked as unsigned long. All of them seem to be unsigned.

7.

> you mean dereference of self or session?

Oops, sorry I mean these calls

```C
+ self->marker_msg_seq_num  = fix_field_unparse_zpad(&FIX_INT_FIELD(MsgSeqNum, 0), FIX_TEMPLATE_MSG_SEQ_NUM_ZPAD, self->const_buf);
+ self->marker_sending_time = fix_field_unparse_zpad(&FIX_STRING_FIELD(SendingTime, "YYYYMMDD-HH:MM:SS.sss"), 0, self->const_buf);
```

They are used here
```C
+void fix_template_unparse(struct fix_template *self, struct fix_session *session)
...
+	modp_litoa10_zpad(session->out_msg_seq_num, FIX_TEMPLATE_MSG_SEQ_NUM_ZPAD, self->marker_msg_seq_num);
...
+	memcpy(self->marker_sending_time, session->str_now, 21); // sizeof("YYYYMMDD-HH:MM:SS.sss")
```
Potential SEGFAULT as far as I can tell

> we've very little != NULL checks actually all over the library

If it is the case that's a real problem. Could you please point me to them? Thanks!

8.

> fixed size of sender_comp_id - difficult to judge, this is where we may need improvements but i'd suggest to keep it for now.

Feel free to make whatever assumptions you want. We just need to remember what  those assumptions are. BTW, why ```sender_comp_id``` is not fixed? Could you please tell in what cases we can have variable ```sender_comp_id```?

12.
> there are different views on whether freeing memory right before exit is a memory leak or a waste of CPU cycles )

Anyway, these are just examples how to use libtrading primitives correctly. These examples are intended for our users who should remember to release resources in their programs. If we don't do it ourselves why should be expect other people do that? :smile:

**Comment by divaykin** [comment]
1. ok, sure

3. sure, will mark all unsigned

7. you mean `FIX_STRING_FIELD(SendingTime, "YYYYMMDD-HH:MM:SS.sss")` could be a problem? sorry i'm blind please help. little `!= NULL` checks - never mind, just most of the time we don't check `self != NULL` but to me it's not a problem at all.

8. variable `sender_comp_id`? once i'll manage to hire you i'll tell you, it's actually very non trivial, you going to like it. you sure you're not interested in seeing any offers?

**Comment by mstanichenko** [comment]
3.
> sorry i'm blind please help

That's not necessary you :smirk:
OK, are there any chances that ```fix_field_unparse_zpad()``` ever fail? Is ```NULL``` a possible return value? If at some point in the future ```fix_field_unparse_zpad()``` returns ```NULL``` we will get SEGFAULT here

```C
memcpy(self->marker_sending_time, session->str_now, 21);
```

as ```self->marker_sending_time``` will be ```NULL```

> little != NULL checks - never mind, just most of the time we don't check self != NULL but to me it's not a problem at all.

Really, if you can spot any case where it might lead to crash we should fix that. That is a real problem. Just show me a case. It might help me to fix some other places as well

4.
> variable sender_comp_id?
Yep :smile:

> once i'll manage to hire you i'll tell you, it's actually very non trivial, you going to like it. you sure you're not interested in seeing any offers?

:smiley:

**Comment by divaykin** [comment]
@mstanichenko I've a bit of a problem with `SendingTime`, maybe you have an idea. it's currently in `const_buf` which is quite wrong because it's not constant. but it does not really belong to `head_buf` neither. i was thinking of just requiring user to manage it.

on other hand `SendingTime` and `TransactTime` could be periodically updated by timer. of course i can introduce yet another buffer for these two fields only.

any suggestions you can give here?

**Comment by divaykin** [comment]
@mstanichenko most of your comments should be addressed, could you please look at the latest version of the patch? thx

**Comment by mstanichenko** [comment]
Hi guys,

It doesn't build for me ;)

> lib/proto/fix_template.c:9:28: fatal error: exanic/fifo_if.h: No such file or directory
 #include <exanic/fifo_if.h>

This must be a typo

>
```C
struct fix_templete_cfg {
```

Below is a terrible commit message

>  templates support - alternative way to format FIX messages efficiently

> @mstackenko comments addressed

> string_8 support added

I can live with the rest for the time being

**Comment by divaykin** [comment]
@mstanichenko sorry about that, I'll implement also `fix_template_send()`, agree it with you and then would rewrite commit history.

**Comment by divaykin** [comment]
@mstanichenko okay how about that? )

**Comment by penberg** [comment]
@divaykin AFAICT, that STRING_8 commit does not need to be there. It's already merged in master.

**Comment by divaykin** [comment]
@penberg I've squashed all in one commit which seems to be not conflicting / do not have STRING_8 in diff right?

**Comment by penberg** [comment]
@divaykin That commit was fine but I think you had an old copy of the STRING_8 commit. I cleaned it up and merged the branch, thanks!

**Pull request closed without merging**
