### PR TITLE
Use EXIT FAILURE in libtrading-config.c for clarity.

### LINKED ISSUE #81: Use EXIT_FAILURE in libtrading-config.c for clarity?
Maybe we could use EXIT_FAILURE in https://github.com/libtrading/libtrading/blob/master/libtrading-config.c#L22

### PR DESCRIPTION
**Pull request by tfarina**
Fixes #81

### CODE REVIEW

**Comment by mstanichenko** [comment]
Thank you @tfarina!

Looks OK to me :-)
Still we need to clean up the other files as well ;-)

**Comment by tfarina** [comment]
Could you guys point me the other files that need cleanup?

**Comment by divaykin** [comment]
@tfarina try using "grep -r main *" to find all the main functions

**Comment by tfarina** [comment]
Are you guys telling me to change something else other than exit() calls? If yes, could explicitly say what is it?

**Comment by divaykin** [comment]
see http://stackoverflow.com/questions/8867871/should-i-return-exit-success-or-0-from-main

**Comment by penberg** [comment]
I merged this pull request but feel free to open a new one to address the other call-sites as pointed out by @divaykin and @mstanichenko.

**Comment by tfarina** [comment]
@penberg I thought https://github.com/tfarina/libtrading/commit/4a56f2f04c3a55e7ea9b80e2c55cdcdd63937b29 had addressed them. Hasn't it?

I think you merged it, but with the original commit message.

(I'm learning pull-request workflow, I'm used to Gerrit and Rietveld codereview tools).

**Comment by penberg** [comment]
@tfarina Right, I didn't realize you had updated the pull request! Thanks!

**Pull request merged**
