### PR TITLE
allow store short string constants inplace

### PR DESCRIPTION
**Pull request by divaykin**

### CODE REVIEW

**Comment by divaykin** [comment]
@penberg what do you think of that? actually most of strings in practice fit into 8 chars

**Comment by divaykin** [comment]
@mstanichenko do you have a view on this? thanks a lot!

**Comment by mstanichenko** [comment]
Hi @divaykin!

Could you please elaborate what is the rationale behind? Do you believe that 'for'-loop would be faster than 'while'-loop? Do you believe that compiler can somehow optimize this loop? If you know how exactly, can we optimize it explicitly?

**Comment by divaykin** [comment]
Hi @mstanichenko it's just easier somewhat to manage memory and copy fields around. Mostly to save on malloc / free calls. Your strings would be also located compact in cache instead of being all around a heap.

**Comment by mstanichenko** [comment]
I wouldn't mind adding it into the code at all.

> Mostly to save on malloc / free calls

What malloc/free calls do you have in mind? The one that are invoked on your side? I can't find anything in the library code.

> Your strings would be also located compact in cache instead of being all around a heap.

It depends how a user manages memory, doesn't it?

@penberg are you OK?

**Comment by divaykin** [comment]
> What malloc/free calls do you have in mind? The one that are invoked on your side?
Yes, one way or another strings has to be allocated / deallocated by the user code
> It depends how a user manages memory, doesn't it?
It's still difficult to place string values close to fix_field array no matter how good you're in managing a memory

**Comment by divaykin** [comment]
@penberg would be greatly appreciated if we could merge this, many thx

**Comment by divaykin** [comment]
thanks a lot Pekka!

**Comment by penberg** [comment]
@divaykin Pulled, thanks!

BTW, I think we could rename FIX_TYPE_SHORT_STR to FIX_TYPE_STRING_8 to make the thing more explicit.

**Comment by divaykin** [comment]
will do

**Pull request merged**
