### PR TITLE
Measure latency with RDTSC, warmup

### PR DESCRIPTION
**Pull request by divaykin**
Monotonic clock is very time consuming. Skip first 1000 measurements if there are enough orders.

### CODE REVIEW

**Comment by divaykin** [comment]
This one is too messy

**Comment by penberg** [comment]
@divaykin I would like to keep libtrading portable across platforms. I'm OK with ``RDTSC`` support as a configurable option. Perhaps there's an existing library we could use for that?

I don't think we should skip measurements during "warmup" period because outliers *do* matter. However, I am thinking of switching to HdrHistogram:

https://github.com/HdrHistogram/HdrHistogram_c

so that we're able to show latency percentiles and not just min/avg/max.

**Comment by divaykin** [comment]
@penberg according to latest micro bench 2 x CLOCK_MONOTONIC is only ~50usec which is acceptable overhead for now so lets leave it.

The `warmup` period is interesting topic - I've an impression that outliers are much more likely to happen during startup - cache is not fully lined up, C state of CPU could be wrong, etc. I'm more interested in `cruise` mode outliers than something specific to initial phase.

Yes, I'll do histograms later on. To me HdrHistogram is somewhat an overkill. 

If we have enough observation we can estimate quantiles with simple one pass:
`quantile += eta * (sgn(sample - quantile) + 2.0 * p - 1.0)`

**Comment by penberg** [comment]
We're already connect to a FIX server and sent and received a logon message when we start measuring. So I doubt CPU cache or page faults play a role here. CPU frequency scaling is a problem but you really need to address that in your system when running such benchmarks. Looking at perf profiles, the tests I'm conducting are dominated by Linux kernel TCP/IP stack so that's a likely source for the outliers.

That said, if you really want to skip first N orders, feel free to implement a command line option for that. What I don't want is to unconditionally and silently do that for everyone.

**Pull request closed without merging**
