### PR TITLE
bugfix - REALTIME clock should be used to print human readable date/time

### PR DESCRIPTION
**Pull request by divaykin**
str_now was wrong because MONOTONIC clock (since boot) were used. basically it used to show year 1970...

### CODE REVIEW

**Comment by penberg** [comment]
@mstanichenko, comments on this?

**Comment by mstanichenko** [comment]
The whole story starts with commit 78d8c618193707d28fc0c0c0263591b3b2071d59
It seems that we are trying to solve issues that arise because of it rather than fixing initial approach.

self->now is not supposed to represent absolute time. For some reason, we assume that it really is and unreasonably  call ```TIMESPEC_TO_TIMEVAL()```

We can have two different functions: the one updates fix session internal clock (self->now) the other is responsible for absolute time string representation. ```fix_session_time_update``` may call either of them or both.

Does it sound reasonable?

**Comment by divaykin** [comment]
@mstanichenko yes it's indeed my commit that introduced a bug sorry about that.

yes we can do two functions instead of one i.e. `fix_session_monotonic_time_update` and `fix_session_realtime_update`? for me it'd be even better because I don't use `self->now` anyway. just let me know your preferences for `fix_session_time_update`.

if you've a lot of sessions and updating all the clocks at the same time calling gettime takes long.

**Comment by mstanichenko** [comment]
> yes it's indeed my commit that introduced a bug sorry about that

No worries about that :)

> yes we can do two functions instead of one i.e.

Agreed

> just let me know your preferences for fix_session_time_update.

I believe we should allow a user explicitly call ```fix_session_monotonic_time_update``` or ```fix_session_realtime_update```. ```fix_session_time_update``` can by default update both counters.

> if you've a lot of sessions and updating all the clocks at the same time calling gettime takes long

Yes of course that makes sense

**Pull request closed without merging**
