### PR TITLE
combined recv and parse flags in fix_session_recv, translation of libtrading recv flags to OS flags, rename some flags

### PR DESCRIPTION
**Pull request by divaykin**
related to #84 in order to pass parse flags to fix_session_recv need to implement flag translation

### CODE REVIEW

**Comment by mstanichenko** [comment]
Looks OK to me.
@divaykin, do we really need ```FIX_RECV_FLAG_MASK```/```FIX_PARSE_FLAG_MASK```?
It looks like we don't have to perform logical AND with these masks.

**Comment by divaykin** [comment]
@mstanichenko thanks removed masks, logical ANDs were indeed redundant

**Comment by penberg** [comment]
@mstanichenko, does this look to you?

**Comment by mstanichenko** [comment]
OK with me

**Pull request merged**
